import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { KycStatus, Prisma, User } from "@prisma/client";
import { unlink } from "fs/promises";
import { PrismaService } from "../prisma/prisma.service";
import { CorporateKycDecisionDto, CorporateKycDocumentType, SaveCorporateKycDto } from "./corporate-kyc.dto";
import { NotificationsService } from "../notifications/notifications.service";

const requiredDocuments = [CorporateKycDocumentType.registration_certificate, CorporateKycDocumentType.tax_certificate, CorporateKycDocumentType.representative_id, CorporateKycDocumentType.bank_proof];
const documentSelect = { id: true, type: true, originalName: true, mimeType: true, size: true, status: true, createdAt: true } as const;

@Injectable()
export class CorporateKycService {
  constructor(private readonly prisma: PrismaService, private readonly notifications: NotificationsService) {}
  private ensureCorporate(user: User) { if (user.accountType !== "corporate") throw new ForbiddenException("Kurumsal KYC yalnız kurumsal hesaplar içindir."); }
  async getMine(user: User) { this.ensureCorporate(user); const application = await this.prisma.corporateKycApplication.upsert({ where: { userId: user.id }, create: { userId: user.id }, update: {}, include: { documents: { select: documentSelect, orderBy: { createdAt: "asc" } }, auditLogs: { orderBy: { createdAt: "desc" }, take: 20 } } }); return this.present(application); }
  async saveDraft(user: User, input: SaveCorporateKycDto) { this.ensureCorporate(user); const current = await this.prisma.corporateKycApplication.findUnique({ where: { userId: user.id } }); if (current?.status === KycStatus.pending || current?.status === KycStatus.approved) throw new BadRequestException("İncelemedeki veya onaylı başvuru değiştirilemez."); this.validateOwners(input); const application = await this.prisma.corporateKycApplication.upsert({ where: { userId: user.id }, create: this.data(user.id, input), update: { ...this.data(user.id, input), userId: undefined, status: KycStatus.not_started, decisionReason: null, reviewedAt: null, reviewedById: null }, include: { documents: { select: documentSelect }, auditLogs: true } }); await this.prisma.corporateKycAuditLog.create({ data: { applicationId: application.id, actorId: user.id, action: "draft_saved" } }); return this.present(application); }
  async addDocument(user: User, type: CorporateKycDocumentType, file: Express.Multer.File) { this.ensureCorporate(user); const application = await this.prisma.corporateKycApplication.upsert({ where: { userId: user.id }, create: { userId: user.id }, update: {} }); if (application.status === KycStatus.pending || application.status === KycStatus.approved) throw new BadRequestException("Bu başvuruya belge eklenemez."); const document = await this.prisma.corporateKycDocument.create({ data: { applicationId: application.id, type, storagePath: file.path, originalName: file.originalname, mimeType: file.mimetype, size: file.size }, select: documentSelect }); await this.prisma.corporateKycAuditLog.create({ data: { applicationId: application.id, actorId: user.id, action: "document_uploaded", metadata: { type, documentId: document.id } } }); return document; }
  async removeDocument(user: User, id: string) { this.ensureCorporate(user); const document = await this.prisma.corporateKycDocument.findFirst({ where: { id, application: { userId: user.id, status: { in: [KycStatus.not_started, KycStatus.rejected] } } } }); if (!document) throw new NotFoundException("Silinebilir belge bulunamadı."); await this.prisma.corporateKycDocument.delete({ where: { id } }); await unlink(document.storagePath).catch(() => undefined); return { success: true }; }
  async submit(user: User) { this.ensureCorporate(user); const application = await this.prisma.corporateKycApplication.findUnique({ where: { userId: user.id }, include: { documents: true } }); if (!application) throw new NotFoundException("KYC başvurusu bulunamadı."); if (application.status === KycStatus.pending || application.status === KycStatus.approved) throw new BadRequestException("Başvuru zaten gönderilmiş."); const missingFields = [application.legalName, application.registrationNumber, application.taxNumber, application.incorporationCountry, application.incorporationDate, application.registeredAddress, application.businessActivity, application.representativeName, application.representativeTitle, application.representativeEmail, application.representativePhone, application.representativeBirthDate].some((value) => !value); if (missingFields || !application.termsAccepted || !application.informationConfirmed || !Array.isArray(application.beneficialOwners) || !application.beneficialOwners.length) throw new BadRequestException("Başvuru bilgileri eksik."); const uploaded = new Set(application.documents.map((item) => item.type)); const missingDocs = requiredDocuments.filter((type) => !uploaded.has(type)); if (missingDocs.length) throw new BadRequestException(`Zorunlu belgeler eksik: ${missingDocs.join(", ")}`); return this.prisma.$transaction(async (tx) => { const updated = await tx.corporateKycApplication.update({ where: { id: application.id }, data: { status: KycStatus.pending, submittedAt: new Date(), decisionReason: null, version: { increment: application.status === KycStatus.rejected ? 1 : 0 } }, include: { documents: { select: documentSelect }, auditLogs: true } }); await tx.financialAccount.upsert({ where: { userId: user.id }, create: { userId: user.id, kycStatus: KycStatus.pending, kycProvider: "manual_corporate" }, update: { kycStatus: KycStatus.pending, kycProvider: "manual_corporate" } }); await tx.corporateKycAuditLog.create({ data: { applicationId: application.id, actorId: user.id, action: "submitted" } }); return this.present(updated); }); }
  async listAdmin(status?: KycStatus) { const items = await this.prisma.corporateKycApplication.findMany({ where: status ? { status } : {}, orderBy: [{ submittedAt: "desc" }, { updatedAt: "desc" }], include: { user: { select: { id: true, name: true, email: true, companyName: true, accountType: true } }, documents: { select: documentSelect } } }); return items.map((item) => this.present(item)); }
  async getAdmin(id: string) { const application = await this.prisma.corporateKycApplication.findUnique({ where: { id }, include: { user: { select: { id: true, name: true, email: true, companyName: true, accountType: true } }, reviewedBy: { select: { id: true, name: true, email: true } }, documents: { select: documentSelect }, auditLogs: { orderBy: { createdAt: "desc" }, include: { actor: { select: { id: true, name: true, email: true } } } } } }); if (!application) throw new NotFoundException("KYC başvurusu bulunamadı."); return this.present(application); }
  async decide(id: string, admin: User, input: CorporateKycDecisionDto) { const application = await this.prisma.corporateKycApplication.findUnique({ where: { id } }); if (!application || application.status !== KycStatus.pending) throw new BadRequestException("Başvuru karar verilebilir durumda değil."); if (input.status === "rejected" && !input.reason?.trim()) throw new BadRequestException("Ret gerekçesi zorunludur."); const status = input.status === "approved" ? KycStatus.approved : KycStatus.rejected; const updated = await this.prisma.$transaction(async (tx) => { const result = await tx.corporateKycApplication.update({ where: { id }, data: { status, reviewedById: admin.id, reviewedAt: new Date(), decisionReason: input.reason?.trim() || null }, include: { documents: { select: documentSelect }, auditLogs: true } }); await tx.financialAccount.upsert({ where: { userId: application.userId }, create: { userId: application.userId, kycStatus: status, kycProvider: "manual_corporate" }, update: { kycStatus: status } }); await tx.corporateKycAuditLog.create({ data: { applicationId: id, actorId: admin.id, action: input.status, note: input.reason?.trim() } }); return result; }); await this.notifications.dispatch({ userId: application.userId, topic: "admin_message", type: "corporate_kyc", title: input.status === "approved" ? "Kurumsal KYC onaylandı" : "Kurumsal KYC için düzenleme gerekli", body: input.reason?.trim() || "Kurumsal hesabınız doğrulandı.", targetType: "corporate_kyc", targetId: id }); return this.present(updated); }
  async documentForUser(user: User, id: string) { const document = await this.prisma.corporateKycDocument.findFirst({ where: { id, application: { userId: user.id } } }); if (!document) throw new NotFoundException("Belge bulunamadı."); return document; }
  async documentForAdmin(id: string) { const document = await this.prisma.corporateKycDocument.findUnique({ where: { id } }); if (!document) throw new NotFoundException("Belge bulunamadı."); return document; }
  private validateOwners(input: SaveCorporateKycDto) { if (!input.beneficialOwners) return; if (!input.beneficialOwners.length) throw new BadRequestException("En az bir nihai faydalanıcı gereklidir."); const total = input.beneficialOwners.reduce((sum, owner) => sum + Number(owner.ownershipPercent), 0); if (input.beneficialOwners.some((owner) => owner.ownershipPercent <= 0 || owner.ownershipPercent > 100) || total > 100.01) throw new BadRequestException("Faydalanıcı oranları geçersiz."); }
  private data(userId: string, input: SaveCorporateKycDto) { return { userId, legalName: input.legalName?.trim(), registrationNumber: input.registrationNumber?.trim(), taxNumber: input.taxNumber?.trim(), incorporationCountry: input.incorporationCountry?.trim(), incorporationDate: input.incorporationDate ? new Date(input.incorporationDate) : undefined, registeredAddress: input.registeredAddress?.trim(), website: input.website === undefined ? undefined : input.website.trim() || null, businessActivity: input.businessActivity?.trim(), representativeName: input.representativeName?.trim(), representativeTitle: input.representativeTitle?.trim(), representativeEmail: input.representativeEmail?.toLowerCase(), representativePhone: input.representativePhone?.trim(), representativeBirthDate: input.representativeBirthDate ? new Date(input.representativeBirthDate) : undefined, beneficialOwners: input.beneficialOwners ? input.beneficialOwners.map((owner) => ({ ...owner })) as Prisma.InputJsonValue : undefined, termsAccepted: input.termsAccepted, informationConfirmed: input.informationConfirmed }; }
  private present(application: any) { return { ...application, beneficialOwners: application.beneficialOwners ?? [], requiredDocumentTypes: requiredDocuments, completion: this.completion(application) }; }
  private completion(application: any) { const fields = [application.legalName, application.registrationNumber, application.taxNumber, application.incorporationCountry, application.registeredAddress, application.businessActivity, application.representativeName, application.representativeEmail]; const fieldScore = fields.filter(Boolean).length / fields.length; const docs = new Set((application.documents ?? []).map((item: any) => item.type)); const docScore = requiredDocuments.filter((type) => docs.has(type)).length / requiredDocuments.length; return Math.round((fieldScore * 0.55 + docScore * 0.35 + (application.termsAccepted && application.informationConfirmed ? 0.1 : 0)) * 100); }
}
