import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, BadgeCheck, Building2, FileUp, Plus, Send, ShieldCheck, Trash2, XCircle } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { BeneficialOwner } from "@konnektora/shared";
import { deleteCorporateKycDocument, getCorporateKyc, getUserSession, saveCorporateKyc, submitCorporateKyc, uploadCorporateKycDocument } from "../lib/api";
import { useLanguage } from "../lib/i18n";

const labels: Record<string, string> = { registration_certificate: "Ticaret sicil belgesi", tax_certificate: "Vergi levhası", representative_id: "Yetkili kimliği", bank_proof: "Banka hesap kanıtı" };
const labelsEn: Record<string, string> = { registration_certificate: "Trade registry certificate", tax_certificate: "Tax certificate", representative_id: "Authorised representative ID", bank_proof: "Proof of bank account" };
export function CorporateKycPage() {
  const { language } = useLanguage(); const t = (tr: string, en: string) => language === "tr" ? tr : en;
  const user = getUserSession(); const client = useQueryClient(); const [step, setStep] = useState(1); const [owners, setOwners] = useState<BeneficialOwner[]>([{ name: "", nationality: "", ownershipPercent: 100, identityNumberLast4: "" }]);
  const query = useQuery({ queryKey: ["corporate-kyc"], queryFn: getCorporateKyc, enabled: user?.accountType === "corporate" }); const refresh = () => client.invalidateQueries({ queryKey: ["corporate-kyc"] });
  useEffect(() => { if (query.data?.beneficialOwners.length) setOwners(query.data.beneficialOwners); }, [query.data?.id]);
  const save = useMutation({ mutationFn: saveCorporateKyc, onSuccess: () => { refresh(); setStep((value) => Math.min(3, value + 1)); } }); const upload = useMutation({ mutationFn: ({ type, file }: { type: string; file: File }) => uploadCorporateKycDocument(type, file), onSuccess: refresh }); const remove = useMutation({ mutationFn: deleteCorporateKycDocument, onSuccess: refresh }); const submit = useMutation({ mutationFn: submitCorporateKyc, onSuccess: () => { refresh(); void client.invalidateQueries({ queryKey: ["finance"] }); } });
  if (!user) return <section className="page empty-state"><ShieldCheck/><h1>{t("Kurumsal KYC", "Corporate KYC")}</h1><Link className="primary-action" to="/login">{t("Giriş yap", "Sign in")}</Link></section>;
  if (user.accountType !== "corporate") return <section className="page empty-state"><Building2/><h1>{t("Kurumsal hesap gerekli", "Corporate account required")}</h1><Link className="primary-action" to="/settings/business">{t("Hesap ayarları", "Account settings")}</Link></section>;
  if (!query.data) return <div className="page finance-state">{t("KYC başvurusu yükleniyor…", "Loading KYC application…")}</div>; const app = query.data;
  function saveForm(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); save.mutate({ ...Object.fromEntries(form), ...(step === 2 ? { beneficialOwners: owners } : {}), ...(step === 3 ? { termsAccepted: form.get("termsAccepted") === "on", informationConfirmed: form.get("informationConfirmed") === "on" } : {}) }); }
  return <div className="page kyc-page"><Link className="back-link" to="/finance"><ArrowLeft size={16}/> {t("Finans merkezine dön", "Back to finance centre")}</Link><header className="kyc-heading"><div><span className="eyebrow">{t("Kurumsal doğrulama", "Corporate verification")}</span><h1>{t("Şirketini doğrula", "Verify your company")}</h1><p>{t("Şirket, yetkili, faydalanıcı ve belge kontrollerini tamamla.", "Complete company, representative, beneficial owner and document checks.")}</p></div><div className={`kyc-status-card ${app.status}`}><ShieldCheck/><strong>{app.status === "approved" ? t("Onaylı", "Approved") : app.status === "pending" ? t("İncelemede", "Under review") : `%${app.completion}`}</strong></div></header>
    {app.status === "approved" ? <section className="kyc-result approved"><BadgeCheck/><h2>{t("Kurumsal hesabınız doğrulandı", "Your corporate account is verified")}</h2><p>{t("Ödeme alma ve para çekme özellikleri aktiftir.", "Payment collection and withdrawals are now active.")}</p></section> : app.status === "pending" ? <section className="kyc-result pending"><ShieldCheck/><h2>{t("Başvurunuz inceleniyor", "Your application is under review")}</h2><p>{t("Karar verildiğinde bildirim alacaksınız.", "You will be notified when a decision is made.")}</p></section> : <>
    {app.status === "rejected" ? <div className="kyc-rejection"><XCircle/><div><strong>{t("Düzenleme gerekli", "Changes required")}</strong><p>{app.decisionReason}</p></div></div> : null}<nav className="kyc-steps">{[[1,t("Şirket", "Company")],[2,t("Yetkili & UBO", "Representative & UBO")],[3,t("Belgeler", "Documents")]].map(([number,label]) => <button key={number} className={step === number ? "active" : ""} onClick={() => setStep(Number(number))}><span>{number}</span>{label}</button>)}</nav>
    <form className="kyc-form" onSubmit={saveForm}>{step === 1 ? <section><h2>{t("Şirket bilgileri", "Company information")}</h2><div className="kyc-form-grid"><Field name="legalName" label={t("Yasal şirket unvanı", "Legal company name")} value={app.legalName}/><Field name="registrationNumber" label={t("Ticaret sicil numarası", "Registration number")} value={app.registrationNumber}/><Field name="taxNumber" label={t("Vergi numarası", "Tax number")} value={app.taxNumber}/><Field name="incorporationCountry" label={t("Kuruluş ülkesi", "Country of incorporation")} value={app.incorporationCountry}/><Field name="incorporationDate" label={t("Kuruluş tarihi", "Date of incorporation")} type="date" value={date(app.incorporationDate)}/><Field name="website" label={t("Web sitesi", "Website")} type="url" value={app.website} optional/><label className="wide">{t("Kayıtlı adres", "Registered address")}<textarea name="registeredAddress" required defaultValue={app.registeredAddress ?? ""}/></label><label className="wide">{t("Faaliyet alanı", "Business activity")}<textarea name="businessActivity" required defaultValue={app.businessActivity ?? ""}/></label></div></section> : null}
    {step === 2 ? <section><h2>{t("Yetkili kişi", "Authorised representative")}</h2><div className="kyc-form-grid"><Field name="representativeName" label={t("Ad soyad", "Full name")} value={app.representativeName ?? user.name}/><Field name="representativeTitle" label={t("Görevi", "Job title")} value={app.representativeTitle}/><Field name="representativeEmail" label={t("E-posta", "Email")} type="email" value={app.representativeEmail ?? user.email}/><Field name="representativePhone" label={t("Telefon", "Phone")} value={app.representativePhone}/><Field name="representativeBirthDate" label={t("Doğum tarihi", "Date of birth")} type="date" value={date(app.representativeBirthDate)}/></div><div className="ubo-heading"><h2>{t("Nihai faydalanıcılar (UBO)", "Ultimate beneficial owners (UBO)")}</h2><button type="button" onClick={() => setOwners((items) => [...items, { name:"", nationality:"", ownershipPercent:0 }])}><Plus size={16}/> {t("Ekle", "Add")}</button></div>{owners.map((owner,index) => <div className="ubo-row" key={index}><input aria-label={t("Ad soyad", "Full name")} required placeholder={t("Ad soyad", "Full name")} value={owner.name} onChange={(e)=>changeOwner(setOwners,index,"name",e.target.value)}/><input aria-label={t("Uyruk", "Nationality")} required placeholder={t("Uyruk", "Nationality")} value={owner.nationality} onChange={(e)=>changeOwner(setOwners,index,"nationality",e.target.value)}/><input aria-label={t("Sahiplik yüzdesi", "Ownership percentage")} required type="number" min="0.01" max="100" step="0.01" value={owner.ownershipPercent} onChange={(e)=>changeOwner(setOwners,index,"ownershipPercent",Number(e.target.value))}/><input aria-label={t("Kimlik son 4 hane", "Last 4 ID digits")} placeholder={t("Kimlik son 4", "Last 4 ID digits")} maxLength={4} value={owner.identityNumberLast4 ?? ""} onChange={(e)=>changeOwner(setOwners,index,"identityNumberLast4",e.target.value)}/><button aria-label={t("Faydalanıcıyı sil", "Remove owner")} type="button" disabled={owners.length===1} onClick={()=>setOwners(items=>items.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></div>)}</section> : null}
    {step === 3 ? <section><h2>{t("Zorunlu belgeler", "Required documents")}</h2><div className="kyc-documents">{app.requiredDocumentTypes.map(type => <article key={type}><div><FileUp/><strong>{(language === "tr" ? labels : labelsEn)[type] ?? type}</strong></div><label className="kyc-upload">{t("Belge seç", "Choose document")}<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate({type,file});}}/></label>{app.documents.filter(doc=>doc.type===type).map(doc=><div className="kyc-file" key={doc.id}><span>{doc.originalName}</span><small>{Math.ceil(doc.size/1024)} KB</small><button aria-label={t("Belgeyi sil", "Delete document")} type="button" onClick={()=>remove.mutate(doc.id)}><Trash2 size={14}/></button></div>)}</article>)}</div><label className="kyc-consent"><input type="checkbox" name="termsAccepted" required defaultChecked={app.termsAccepted}/> {t("KYC ve belge işleme koşullarını kabul ediyorum.", "I accept the KYC and document processing terms.")}</label><label className="kyc-consent"><input type="checkbox" name="informationConfirmed" required defaultChecked={app.informationConfirmed}/> {t("Bilgilerin doğru ve güncel olduğunu onaylıyorum.", "I confirm that the information is accurate and up to date.")}</label></section> : null}
    <div className="kyc-form-actions"><button className="finance-primary" disabled={save.isPending}>{step<3 ? t("Kaydet ve devam et", "Save and continue") : t("Taslağı kaydet", "Save draft")}</button>{step===3 ? <button className="kyc-submit" type="button" disabled={submit.isPending || app.completion<90} onClick={()=>submit.mutate()}><Send size={16}/> {t("İncelemeye gönder", "Submit for review")}</button>:null}</div>{save.isError||upload.isError||submit.isError?<p className="form-error">{t("Zorunlu alanları ve belgeleri kontrol edin.", "Check the required fields and documents.")}</p>:null}</form></>}
  </div>;
}
function Field({name,label,value,type="text",optional=false}:{name:string;label:string;value?:string|null;type?:string;optional?:boolean}){return <label>{label}<input name={name} type={type} required={!optional} defaultValue={value??""}/></label>}
function date(value:string|Date|null|undefined){return value?new Date(value).toISOString().slice(0,10):""}
function changeOwner(setter:React.Dispatch<React.SetStateAction<BeneficialOwner[]>>,index:number,key:keyof BeneficialOwner,value:string|number){setter(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item))}
