import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, BadgeCheck, Building2, FileUp, Plus, Send, ShieldCheck, Trash2, XCircle } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { BeneficialOwner } from "@konnektora/shared";
import { deleteCorporateKycDocument, getCorporateKyc, getUserSession, saveCorporateKyc, submitCorporateKyc, uploadCorporateKycDocument } from "../lib/api";

const labels: Record<string, string> = { registration_certificate: "Ticaret sicil belgesi", tax_certificate: "Vergi levhası", representative_id: "Yetkili kimliği", bank_proof: "Banka hesap kanıtı" };
export function CorporateKycPage() {
  const user = getUserSession(); const client = useQueryClient(); const [step, setStep] = useState(1); const [owners, setOwners] = useState<BeneficialOwner[]>([{ name: "", nationality: "", ownershipPercent: 100, identityNumberLast4: "" }]);
  const query = useQuery({ queryKey: ["corporate-kyc"], queryFn: getCorporateKyc, enabled: user?.accountType === "corporate" }); const refresh = () => client.invalidateQueries({ queryKey: ["corporate-kyc"] });
  useEffect(() => { if (query.data?.beneficialOwners.length) setOwners(query.data.beneficialOwners); }, [query.data?.id]);
  const save = useMutation({ mutationFn: saveCorporateKyc, onSuccess: () => { refresh(); setStep((value) => Math.min(3, value + 1)); } }); const upload = useMutation({ mutationFn: ({ type, file }: { type: string; file: File }) => uploadCorporateKycDocument(type, file), onSuccess: refresh }); const remove = useMutation({ mutationFn: deleteCorporateKycDocument, onSuccess: refresh }); const submit = useMutation({ mutationFn: submitCorporateKyc, onSuccess: () => { refresh(); void client.invalidateQueries({ queryKey: ["finance"] }); } });
  if (!user) return <section className="page empty-state"><ShieldCheck/><h1>Kurumsal KYC</h1><Link className="primary-action" to="/login">Giriş yap</Link></section>;
  if (user.accountType !== "corporate") return <section className="page empty-state"><Building2/><h1>Kurumsal hesap gerekli</h1><Link className="primary-action" to="/settings/business">Hesap ayarları</Link></section>;
  if (!query.data) return <div className="page finance-state">KYC başvurusu yükleniyor…</div>; const app = query.data;
  function saveForm(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); save.mutate({ ...Object.fromEntries(form), ...(step === 2 ? { beneficialOwners: owners } : {}), ...(step === 3 ? { termsAccepted: form.get("termsAccepted") === "on", informationConfirmed: form.get("informationConfirmed") === "on" } : {}) }); }
  return <div className="page kyc-page"><Link className="back-link" to="/finance"><ArrowLeft size={16}/> Finans merkezine dön</Link><header className="kyc-heading"><div><span className="eyebrow">Kurumsal doğrulama</span><h1>Şirketini doğrula</h1><p>Şirket, yetkili, faydalanıcı ve belge kontrollerini tamamla.</p></div><div className={`kyc-status-card ${app.status}`}><ShieldCheck/><strong>{app.status === "approved" ? "Onaylı" : app.status === "pending" ? "İncelemede" : `%${app.completion}`}</strong></div></header>
    {app.status === "approved" ? <section className="kyc-result approved"><BadgeCheck/><h2>Kurumsal hesabınız doğrulandı</h2><p>Ödeme alma ve para çekme özellikleri aktiftir.</p></section> : app.status === "pending" ? <section className="kyc-result pending"><ShieldCheck/><h2>Başvurunuz inceleniyor</h2><p>Karar verildiğinde bildirim alacaksınız.</p></section> : <>
    {app.status === "rejected" ? <div className="kyc-rejection"><XCircle/><div><strong>Düzenleme gerekli</strong><p>{app.decisionReason}</p></div></div> : null}<nav className="kyc-steps">{[[1,"Şirket"],[2,"Yetkili & UBO"],[3,"Belgeler"]].map(([number,label]) => <button key={number} className={step === number ? "active" : ""} onClick={() => setStep(Number(number))}><span>{number}</span>{label}</button>)}</nav>
    <form className="kyc-form" onSubmit={saveForm}>{step === 1 ? <section><h2>Şirket bilgileri</h2><div className="kyc-form-grid"><Field name="legalName" label="Yasal şirket unvanı" value={app.legalName}/><Field name="registrationNumber" label="Ticaret sicil numarası" value={app.registrationNumber}/><Field name="taxNumber" label="Vergi numarası" value={app.taxNumber}/><Field name="incorporationCountry" label="Kuruluş ülkesi" value={app.incorporationCountry}/><Field name="incorporationDate" label="Kuruluş tarihi" type="date" value={date(app.incorporationDate)}/><Field name="website" label="Web sitesi" type="url" value={app.website} optional/><label className="wide">Kayıtlı adres<textarea name="registeredAddress" required defaultValue={app.registeredAddress ?? ""}/></label><label className="wide">Faaliyet alanı<textarea name="businessActivity" required defaultValue={app.businessActivity ?? ""}/></label></div></section> : null}
    {step === 2 ? <section><h2>Yetkili kişi</h2><div className="kyc-form-grid"><Field name="representativeName" label="Ad soyad" value={app.representativeName ?? user.name}/><Field name="representativeTitle" label="Görevi" value={app.representativeTitle}/><Field name="representativeEmail" label="E-posta" type="email" value={app.representativeEmail ?? user.email}/><Field name="representativePhone" label="Telefon" value={app.representativePhone}/><Field name="representativeBirthDate" label="Doğum tarihi" type="date" value={date(app.representativeBirthDate)}/></div><div className="ubo-heading"><h2>Nihai faydalanıcılar (UBO)</h2><button type="button" onClick={() => setOwners((items) => [...items, { name:"", nationality:"", ownershipPercent:0 }])}><Plus size={16}/> Ekle</button></div>{owners.map((owner,index) => <div className="ubo-row" key={index}><input required placeholder="Ad soyad" value={owner.name} onChange={(e)=>changeOwner(setOwners,index,"name",e.target.value)}/><input required placeholder="Uyruk" value={owner.nationality} onChange={(e)=>changeOwner(setOwners,index,"nationality",e.target.value)}/><input required type="number" min="0.01" max="100" step="0.01" value={owner.ownershipPercent} onChange={(e)=>changeOwner(setOwners,index,"ownershipPercent",Number(e.target.value))}/><input placeholder="Kimlik son 4" maxLength={4} value={owner.identityNumberLast4 ?? ""} onChange={(e)=>changeOwner(setOwners,index,"identityNumberLast4",e.target.value)}/><button type="button" disabled={owners.length===1} onClick={()=>setOwners(items=>items.filter((_,i)=>i!==index))}><Trash2 size={16}/></button></div>)}</section> : null}
    {step === 3 ? <section><h2>Zorunlu belgeler</h2><div className="kyc-documents">{app.requiredDocumentTypes.map(type => <article key={type}><div><FileUp/><strong>{labels[type] ?? type}</strong></div><label className="kyc-upload">Belge seç<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate({type,file});}}/></label>{app.documents.filter(doc=>doc.type===type).map(doc=><div className="kyc-file" key={doc.id}><span>{doc.originalName}</span><small>{Math.ceil(doc.size/1024)} KB</small><button type="button" onClick={()=>remove.mutate(doc.id)}><Trash2 size={14}/></button></div>)}</article>)}</div><label className="kyc-consent"><input type="checkbox" name="termsAccepted" required defaultChecked={app.termsAccepted}/> KYC ve belge işleme koşullarını kabul ediyorum.</label><label className="kyc-consent"><input type="checkbox" name="informationConfirmed" required defaultChecked={app.informationConfirmed}/> Bilgilerin doğru ve güncel olduğunu onaylıyorum.</label></section> : null}
    <div className="kyc-form-actions"><button className="finance-primary" disabled={save.isPending}>{step<3 ? "Kaydet ve devam et" : "Taslağı kaydet"}</button>{step===3 ? <button className="kyc-submit" type="button" disabled={submit.isPending || app.completion<90} onClick={()=>submit.mutate()}><Send size={16}/> İncelemeye gönder</button>:null}</div>{save.isError||upload.isError||submit.isError?<p className="form-error">Zorunlu alanları ve belgeleri kontrol edin.</p>:null}</form></>}
  </div>;
}
function Field({name,label,value,type="text",optional=false}:{name:string;label:string;value?:string|null;type?:string;optional?:boolean}){return <label>{label}<input name={name} type={type} required={!optional} defaultValue={value??""}/></label>}
function date(value:string|Date|null|undefined){return value?new Date(value).toISOString().slice(0,10):""}
function changeOwner(setter:React.Dispatch<React.SetStateAction<BeneficialOwner[]>>,index:number,key:keyof BeneficialOwner,value:string|number){setter(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item))}
