import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Banknote, Building2, CircleDollarSign, CreditCard, Landmark, ReceiptText, ShieldCheck, WalletCards } from "lucide-react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { getFinanceDashboard, getUserSession, requestPayout, startFinanceKyc, updateFinanceSettings } from "../lib/api";

const statusLabel: Record<string, string> = { pending: "Bekliyor", succeeded: "Başarılı", failed: "Başarısız", refunded: "İade edildi", partially_refunded: "Kısmi iade", cancelled: "İptal" };
export function FinancePage() {
  const user = getUserSession(); const client = useQueryClient(); const finance = useQuery({ queryKey: ["finance"], queryFn: getFinanceDashboard, enabled: Boolean(user) }); const refresh = () => client.invalidateQueries({ queryKey: ["finance"] });
  const settings = useMutation({ mutationFn: (input: Parameters<typeof updateFinanceSettings>[0]) => updateFinanceSettings(input), onSuccess: refresh });
  const kyc = useMutation({ mutationFn: startFinanceKyc, onSuccess: refresh });
  const payout = useMutation({ mutationFn: requestPayout, onSuccess: refresh });
  if (!user) return <section className="page empty-state"><WalletCards size={42}/><h1>Ödemeler ve finans</h1><p>Finansal bilgilerini görmek için giriş yap.</p><Link className="primary-action" to="/account">Giriş yap</Link></section>;
  if (finance.isLoading) return <div className="page finance-state">Finans bilgileri yükleniyor…</div>;
  if (finance.isError || !finance.data) return <div className="page empty-state"><h1>Finans bilgileri yüklenemedi</h1><p>API veya veritabanı bağlantısını kontrol edin.</p></div>;
  const data = finance.data; const business = user.accountType === "corporate";
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); settings.mutate(Object.fromEntries([...form.entries()].map(([key, value]) => [key, String(value).trim() || undefined])) as Parameters<typeof updateFinanceSettings>[0]); }
  return <main className="page finance-page"><header className="finance-heading"><div><span className="eyebrow">Business & ödeme ayarları</span><h1>Finans merkezi</h1><p>Gelir, bakiye, ödeme, iade ve kurumsal doğrulamalarını tek yerden yönet.</p></div><div className={`kyc-pill ${data.account.kycStatus}`}><ShieldCheck size={18}/><span>KYC</span><strong>{data.account.kycStatus === "approved" ? "Onaylı" : data.account.kycStatus === "pending" ? "İnceleniyor" : "Tamamlanmadı"}</strong></div></header>
    <section className="finance-metrics"><Metric icon={<WalletCards/>} label="Kullanılabilir bakiye" value={money(data.summary.availableBalance, data.summary.currency)}/><Metric icon={<Banknote/>} label="Bekleyen bakiye" value={money(data.summary.pendingBalance, data.summary.currency)}/><Metric icon={<CircleDollarSign/>} label="Toplam net gelir" value={money(data.summary.lifetimeNetRevenue, data.summary.currency)}/></section>
    {!business ? <section className="finance-notice"><Building2 size={24}/><div><strong>Kurumsal finans özellikleri</strong><p>Banka bağlantısı, KYC, fatura bilgileri ve para çekme yalnız kurumsal hesaplarda kullanılabilir.</p></div><Link to="/account">Hesap türünü yönet</Link></section> : <div className="finance-grid"><section className="finance-panel"><h2><ReceiptText size={20}/> Fatura ve vergi bilgileri</h2><form onSubmit={save}><label>Yasal şirket/unvan<input name="legalName" defaultValue={data.billing?.legalName ?? ""}/></label><div className="finance-row"><label>Vergi numarası<input name="taxNumber" defaultValue={data.billing?.taxNumber ?? ""}/></label><label>Vergi dairesi<input name="taxOffice" defaultValue={data.billing?.taxOffice ?? ""}/></label></div><label>Fatura e-postası<input type="email" name="billingEmail" defaultValue={data.billing?.billingEmail ?? user.email}/></label><div className="finance-row"><label>Ülke<input name="country" defaultValue={data.billing?.country ?? ""}/></label><label>Şehir<input name="city" defaultValue={data.billing?.city ?? ""}/></label></div><label>Adres<textarea name="addressLine" defaultValue={data.billing?.addressLine ?? ""}/></label><h2><Landmark size={20}/> Ödeme alma hesabı</h2><div className="finance-row"><label>Para birimi<select name="preferredCurrency" defaultValue={data.account.preferredCurrency}><option>TRY</option><option>EUR</option><option>USD</option><option>GBP</option></select></label><label>Banka sağlayıcısı<input name="bankProvider" defaultValue={data.account.bankProvider ?? ""}/></label></div><label>Hesap etiketi<input name="bankAccountLabel" defaultValue={data.account.bankAccountLabel ?? ""}/></label><label>Hesabın son 4 hanesi<input name="bankAccountLast4" inputMode="numeric" minLength={4} maxLength={4} defaultValue={data.account.bankAccountLast4 ?? ""}/></label><button className="finance-primary" disabled={settings.isPending}>{settings.isPending ? "Kaydediliyor…" : "Ayarları kaydet"}</button></form></section>
      <aside className="finance-side"><section className="finance-panel"><h2><ShieldCheck size={20}/> Kimlik doğrulama</h2><p>Ödeme alabilmek ve para çekebilmek için şirket/kişi doğrulamasını tamamla.</p><button className="finance-secondary" disabled={data.account.kycStatus === "pending" || data.account.kycStatus === "approved" || kyc.isPending} onClick={() => kyc.mutate()}>{data.account.kycStatus === "approved" ? <><BadgeCheck size={18}/> Doğrulandı</> : "KYC sürecini başlat"}</button></section><section className="finance-panel"><h2><CreditCard size={20}/> Para çek</h2><form onSubmit={(event) => { event.preventDefault(); payout.mutate(Number(new FormData(event.currentTarget).get("amount"))); }}><label>Tutar<input name="amount" type="number" min="1" max={data.summary.availableBalance} step="0.01" required/></label><button className="finance-secondary" disabled={payout.isPending || data.account.kycStatus !== "approved"}>Para çekme talebi oluştur</button></form></section></aside></div>}
    <section className="finance-panel finance-transactions"><h2><ReceiptText size={20}/> İşlem geçmişi</h2>{data.transactions.length ? <div className="transaction-table"><div className="transaction-head"><span>İşlem</span><span>Durum</span><span>Tarih</span><span>Tutar</span></div>{data.transactions.map((item) => { const incoming = item.payeeId === user.id; return <div key={item.id}><span><strong>{item.event?.title ?? "Etkinlik ödemesi"}</strong><small>{incoming ? `${item.payer?.name ?? "Katılımcı"} tarafından` : `${item.payee?.name ?? "Organizatör"} için`}</small></span><span className={`transaction-status ${item.status}`}>{statusLabel[item.status]}</span><span>{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium" }).format(new Date(item.createdAt))}</span><strong className={incoming ? "money-in" : "money-out"}>{incoming ? "+" : "-"}{money(incoming ? item.netAmount : item.grossAmount, item.currency)}</strong></div>})}</div> : <div className="finance-empty">Henüz finansal işlem yok.</div>}</section>
  </main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article>{icon}<span>{label}</span><strong>{value}</strong></article>; }
function money(amount: number, currency: string) { return new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(amount); }
