import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BadgeCheck, Banknote, BarChart3, Building2, Check, CircleDollarSign, CreditCard, Landmark, PackageCheck, ReceiptText, ShieldCheck, Store, WalletCards } from "lucide-react";
import type { FormEvent } from "react";
import { Link } from "react-router-dom";
import { ServiceFeedback } from "../components/ServiceFeedback";
import { changeBusinessPlan, getFinanceDashboard, getUserSession, requestPayout, updateFinanceSettings } from "../lib/api";
import { useLanguage } from "../lib/i18n";

const statusLabel: Record<string, string> = { pending: "Bekliyor", succeeded: "Başarılı", failed: "Başarısız", refunded: "İade edildi", partially_refunded: "Kısmi iade", cancelled: "İptal" };
const statusLabelEn: Record<string, string> = { pending: "Pending", succeeded: "Successful", failed: "Failed", refunded: "Refunded", partially_refunded: "Partially refunded", cancelled: "Cancelled" };
export function FinancePage() {
  const { language } = useLanguage(); const t = (tr: string, en: string) => language === "tr" ? tr : en; const locale = language === "tr" ? "tr-TR" : "en-GB";
  const user = getUserSession(); const client = useQueryClient(); const finance = useQuery({ queryKey: ["finance"], queryFn: getFinanceDashboard, enabled: Boolean(user) }); const refresh = () => client.invalidateQueries({ queryKey: ["finance"] });
  const settings = useMutation({ mutationFn: (input: Parameters<typeof updateFinanceSettings>[0]) => updateFinanceSettings(input), onSuccess: refresh });
  const payout = useMutation({ mutationFn: requestPayout, onSuccess: refresh });
  const plan = useMutation({ mutationFn: (selected: "starter" | "growth" | "scale") => changeBusinessPlan(selected, selected === "starter" ? undefined : `pm_sandbox_${crypto.randomUUID()}`), onSuccess: refresh });
  if (!user) return <section className="page empty-state"><WalletCards size={42}/><h1>{t("Ödemeler ve finans", "Payments and finance")}</h1><p>{t("Finansal bilgilerini görmek için giriş yap.", "Sign in to view your financial information.")}</p><Link className="primary-action" to="/login">{t("Giriş yap", "Sign in")}</Link></section>;
  if (finance.isLoading) return <div className="page finance-state"><h1>{t("İşletme merkezi", "Business centre")}</h1><p>{t("Finans bilgileri yükleniyor…", "Loading financial information…")}</p></div>;
  if (finance.isError || !finance.data) return <div className="page empty-state"><h1>{t("İşletme merkezi", "Business centre")}</h1><ServiceFeedback error={finance.error} fallback={t("Finans bilgilerin şu anda yüklenemedi. Biraz sonra yeniden deneyebilirsin.", "Your financial information could not be loaded. Please try again shortly.")} onRetry={() => void finance.refetch()} title={t("Finans bilgileri yüklenemedi", "Financial information could not be loaded")}/></div>;
  const data = finance.data; const business = user.accountType === "corporate";
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); settings.mutate(Object.fromEntries([...form.entries()].map(([key, value]) => [key, String(value).trim() || undefined])) as Parameters<typeof updateFinanceSettings>[0]); }
  return <div className="page finance-page"><header className="finance-heading"><div><span className="eyebrow">{t("İşletme, mağaza ve ödemeler", "Business, store and payments")}</span><h1>{t("İşletme merkezi", "Business centre")}</h1><p>{t("Paketini, etkinliklerini, mekânlarını, gelirini ve kurumsal doğrulamalarını tek sayfadan yönet.", "Manage your plan, events, places, revenue and corporate verification from one page.")}</p></div><div className={`kyc-pill ${data.account.kycStatus}`}><ShieldCheck size={18}/><span>KYC</span><strong>{data.account.kycStatus === "approved" ? t("Onaylı", "Approved") : data.account.kycStatus === "pending" ? t("İnceleniyor", "Under review") : t("Tamamlanmadı", "Incomplete")}</strong></div></header>
    <section className="business-overview"><article><Building2/><span>{t("İşletme", "Business")}</span><strong>{data.business.companyName || user.name}</strong><small>{data.business.category || t("Kategori belirtilmedi", "Category not specified")}</small></article><article><BarChart3/><span>{t("Yönetilen içerik", "Managed content")}</span><strong>{data.business.managedEventCount} {t("etkinlik", "events")}</strong><small>{data.business.managedPlaceCount} {t("mekân", "places")}</small></article><article><PackageCheck/><span>{t("Aktif paket", "Active plan")}</span><strong>{data.business.plan === "starter" ? t("Başlangıç", "Starter") : data.business.plan === "growth" ? t("Büyüme", "Growth") : t("Ölçek", "Scale")}</strong><small>{data.business.planStartedAt ? t(`${new Date(data.business.planStartedAt).toLocaleDateString(locale)} tarihinden beri`, `Since ${new Date(data.business.planStartedAt).toLocaleDateString(locale)}`) : t("Standart paket", "Standard plan")}</small></article></section>
    <section className="finance-metrics"><Metric icon={<WalletCards/>} label={t("Kullanılabilir bakiye", "Available balance")} value={money(data.summary.availableBalance, data.summary.currency, locale)}/><Metric icon={<Banknote/>} label={t("Bekleyen bakiye", "Pending balance")} value={money(data.summary.pendingBalance, data.summary.currency, locale)}/><Metric icon={<CircleDollarSign/>} label={t("Toplam net gelir", "Lifetime net revenue")} value={money(data.summary.lifetimeNetRevenue, data.summary.currency, locale)}/></section>
    <section className="finance-panel business-store"><header><div><span className="eyebrow"><Store size={16}/> {t("Paket mağazası", "Plan store")}</span><h2>{t("İşletmene uygun paketi seç", "Choose the right plan for your business")}</h2></div><p>{t("Paket değişiklikleri anında hesabına uygulanır.", "Plan changes are applied to your account immediately.")}</p></header><div className="business-plan-grid">{([
      { id: "starter", name: t("Başlangıç", "Starter"), price: t("Ücretsiz", "Free"), features: [t("Etkinlik ve mekân oluşturma", "Create events and places"), t("Temel davet yönetimi", "Basic invitation management"), t("Gelir özeti", "Revenue summary")] },
      { id: "growth", name: t("Büyüme", "Growth"), price: t("₺499 / ay", "TRY 499 / month"), features: [t("Gelişmiş katılımcı yönetimi", "Advanced attendee management"), t("Öncelikli keşif görünürlüğü", "Priority discovery visibility"), t("Finans ve performans raporları", "Finance and performance reports")] },
      { id: "scale", name: t("Ölçek", "Scale"), price: t("₺1.499 / ay", "TRY 1,499 / month"), features: [t("Sınırsız yönetici", "Unlimited managers"), t("Gelişmiş işletme araçları", "Advanced business tools"), t("Öncelikli destek", "Priority support")] },
    ] as const).map((item) => <article className={data.business.plan === item.id ? "selected" : ""} key={item.id}><div><h3>{item.name}</h3><strong>{item.price}</strong></div><ul>{item.features.map((feature) => <li key={feature}><Check size={16}/>{feature}</li>)}</ul><button className={data.business.plan === item.id ? "finance-secondary" : "finance-primary"} disabled={data.business.plan === item.id || plan.isPending || (item.id !== "starter" && !business)} onClick={() => plan.mutate(item.id)}>{data.business.plan === item.id ? t("Aktif paket", "Active plan") : item.id !== "starter" && !business ? t("Kurumsal hesap gerekli", "Corporate account required") : t("Paketi seç", "Choose plan")}</button></article>)}</div>{plan.isError ? <p className="form-error">{t("Paket değiştirilemedi. Kurumsal hesap ve ödeme bilgilerini kontrol et.", "The plan could not be changed. Check your corporate account and payment details.")}</p> : null}</section>
    {!business ? <section className="finance-notice"><Building2 size={24}/><div><strong>{t("Kurumsal finans özellikleri", "Corporate finance features")}</strong><p>{t("Banka bağlantısı, KYC, fatura bilgileri ve para çekme yalnız kurumsal hesaplarda kullanılabilir.", "Bank connection, KYC, billing details and withdrawals are available only to corporate accounts.")}</p></div><Link to="/settings/business">{t("Hesap türünü yönet", "Manage account type")}</Link></section> : <div className="finance-grid"><section className="finance-panel"><h2><ReceiptText size={20}/> {t("Fatura ve vergi bilgileri", "Billing and tax details")}</h2><form onSubmit={save}><label>{t("Yasal şirket/unvan", "Legal company name")}<input name="legalName" defaultValue={data.billing?.legalName ?? ""}/></label><div className="finance-row"><label>{t("Vergi numarası", "Tax number")}<input name="taxNumber" defaultValue={data.billing?.taxNumber ?? ""}/></label><label>{t("Vergi dairesi", "Tax office")}<input name="taxOffice" defaultValue={data.billing?.taxOffice ?? ""}/></label></div><label>{t("Fatura e-postası", "Billing email")}<input type="email" name="billingEmail" defaultValue={data.billing?.billingEmail ?? user.email}/></label><div className="finance-row"><label>{t("Ülke", "Country")}<input name="country" defaultValue={data.billing?.country ?? ""}/></label><label>{t("Şehir", "City")}<input name="city" defaultValue={data.billing?.city ?? ""}/></label></div><label>{t("Adres", "Address")}<textarea name="addressLine" defaultValue={data.billing?.addressLine ?? ""}/></label><h2><Landmark size={20}/> {t("Ödeme alma hesabı", "Payout account")}</h2><div className="finance-row"><label>{t("Para birimi", "Currency")}<select name="preferredCurrency" defaultValue={data.account.preferredCurrency}><option>TRY</option><option>EUR</option><option>USD</option><option>GBP</option></select></label><label>{t("Banka sağlayıcısı", "Bank provider")}<input name="bankProvider" defaultValue={data.account.bankProvider ?? ""}/></label></div><label>{t("Hesap etiketi", "Account label")}<input name="bankAccountLabel" defaultValue={data.account.bankAccountLabel ?? ""}/></label><label>{t("Hesabın son 4 hanesi", "Last 4 account digits")}<input name="bankAccountLast4" inputMode="numeric" minLength={4} maxLength={4} defaultValue={data.account.bankAccountLast4 ?? ""}/></label><button className="finance-primary" disabled={settings.isPending}>{settings.isPending ? t("Kaydediliyor…", "Saving…") : t("Ayarları kaydet", "Save settings")}</button></form></section>
      <aside className="finance-side"><section className="finance-panel"><h2><ShieldCheck size={20}/> {t("Kurumsal doğrulama", "Corporate verification")}</h2><p>{t("Şirket, yetkili, sahiplik ve belgeleri doğrulayarak ödeme alma özelliklerini aç.", "Verify the company, representative, ownership and documents to enable payment collection.")}</p><Link className="finance-secondary" to="/finance/kyc">{data.account.kycStatus === "approved" ? <><BadgeCheck size={18}/> {t("Doğrulandı", "Verified")}</> : data.account.kycStatus === "pending" ? t("Başvuruyu görüntüle", "View application") : t("KYC başvurusunu tamamla", "Complete KYC application")}</Link></section><section className="finance-panel"><h2><CreditCard size={20}/> {t("Para çek", "Withdraw funds")}</h2><form onSubmit={(event) => { event.preventDefault(); payout.mutate(Number(new FormData(event.currentTarget).get("amount"))); }}><label>{t("Tutar", "Amount")}<input name="amount" type="number" min="1" max={data.summary.availableBalance} step="0.01" required/></label><button className="finance-secondary" disabled={payout.isPending || data.account.kycStatus !== "approved"}>{t("Para çekme talebi oluştur", "Create withdrawal request")}</button></form></section></aside></div>}
    <section className="finance-panel finance-transactions"><h2><ReceiptText size={20}/> {t("İşlem geçmişi", "Transaction history")}</h2>{data.transactions.length ? <div className="transaction-table"><div className="transaction-head"><span>{t("İşlem", "Transaction")}</span><span>{t("Durum", "Status")}</span><span>{t("Tarih", "Date")}</span><span>{t("Tutar", "Amount")}</span></div>{data.transactions.map((item) => { const incoming = item.payeeId === user.id; return <div key={item.id}><span><strong>{item.event?.title ?? t("Etkinlik ödemesi", "Event payment")}</strong><small>{incoming ? t(`${item.payer?.name ?? "Katılımcı"} tarafından`, `From ${item.payer?.name ?? "Attendee"}`) : t(`${item.payee?.name ?? "Organizatör"} için`, `For ${item.payee?.name ?? "Organiser"}`)}</small></span><span className={`transaction-status ${item.status}`}>{(language === "tr" ? statusLabel : statusLabelEn)[item.status] ?? item.status}</span><span>{new Intl.DateTimeFormat(locale, { dateStyle: "medium" }).format(new Date(item.createdAt))}</span><strong className={incoming ? "money-in" : "money-out"}>{incoming ? "+" : "-"}{money(incoming ? item.netAmount : item.grossAmount, item.currency, locale)}</strong></div>})}</div> : <div className="finance-empty">{t("Henüz finansal işlem yok.", "There are no financial transactions yet.")}</div>}</section>
  </div>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article>{icon}<span>{label}</span><strong>{value}</strong></article>; }
function money(amount: number, currency: string, locale: string) { return new Intl.NumberFormat(locale, { style: "currency", currency }).format(amount); }
