import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Ban, Check, CheckCheck, Edit3, File, Flag, ImagePlus, MessageCircle, MoreVertical, Pin, Reply, Search, Send, Smile, Trash2, Volume2, VolumeX, X } from "lucide-react";
import type { FormEvent } from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { RichText } from "../components/RichText";
import { UserIdentityLink, userProfilePath } from "../components/UserIdentityLink";
import { ReportDialog } from "../components/ReportDialog";
import type { PrivateChatMessage } from "@konnektora/shared";
import { createBlock, deleteConversation, deletePrivateMessage, editPrivateMessage, getTyping, getUserSession, listConversationMessages, listConversations, listMemberSuggestions, markConversationRead, searchDiscovery, searchPrivateMessages, sendPrivateMessage, sendTyping, toggleMessageReaction, updateConversationPreference } from "../lib/api";

const emojis = ["❤️", "👍", "😂", "😮", "😢", "🎉"];

export function MessagesPage() {
  const user = getUserSession(); const [params, setParams] = useSearchParams(); const client = useQueryClient();
  const peerId = params.get("peer") ?? ""; const [query, setQuery] = useState(""); const [recipientQuery, setRecipientQuery] = useState(""); const [recipientFocused, setRecipientFocused] = useState(false);
  const conversations = useQuery({ queryKey: ["conversations", user?.id], queryFn: listConversations, enabled: Boolean(user), refetchInterval: 15_000 });
  const suggestions = useQuery({ queryKey: ["member-suggestions", user?.id], queryFn: listMemberSuggestions, enabled: Boolean(user) });
  const messages = useQuery({ queryKey: ["conversation-messages", peerId], queryFn: () => listConversationMessages(peerId), enabled: Boolean(user && peerId), refetchInterval: 5_000 });
  const typing = useQuery({ queryKey: ["typing", peerId], queryFn: () => getTyping(peerId), enabled: Boolean(user && peerId), refetchInterval: 2_000 });
  const searchResults = useQuery({ queryKey: ["message-search", query], queryFn: () => searchPrivateMessages(query), enabled: query.trim().length >= 2 });
  const recipientResults = useQuery({ queryKey: ["message-recipient-search", recipientQuery], queryFn: () => searchDiscovery(recipientQuery), enabled: recipientQuery.trim().length >= 2 });
  const refresh = () => { void client.invalidateQueries({ queryKey: ["conversation-messages", peerId] }); void client.invalidateQueries({ queryKey: ["conversations"] }); };
  useEffect(() => { const selected = conversations.data?.items.find((item) => item.peer.id === peerId); if (selected?.unreadCount) void markConversationRead(peerId).then(refresh); }, [peerId, conversations.data?.items]);
  if (!user) return <section className="page empty-state"><MessageCircle size={40}/><h1>Mesajlar</h1><p>Konuşmalarını görmek için giriş yap.</p><Link className="primary-action" to="/login">Giriş yap</Link></section>;
  const list = conversations.data?.items ?? [];
  const selectedConversation = conversations.data?.items.find((item) => item.peer.id === peerId);
  const suggested = suggestions.data?.find((item) => item.id === peerId);
  const peer = selectedConversation?.peer ?? (suggested ? { id: suggested.id, name: suggested.name, username: suggested.username, status: "active" as const } : null);
  const newRecipients = (suggestions.data ?? []).filter((item) => item.id !== user.id && !(conversations.data?.items ?? []).some((conversation) => conversation.peer.id === item.id));
  return <section className={`page messages-layout advanced-messages${peerId ? " has-selection" : ""}`}>
    <aside className="conversation-sidebar"><div className="message-sidebar-head"><div><h1>Mesajlar</h1><span>{conversations.data?.totalUnread ?? 0} okunmamış</span></div></div>
      <div className="message-search"><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Mesajlarda ara…"/><>{query ? <button onClick={() => setQuery("")}><X size={15}/></button> : null}</></div>
      {query.trim().length >= 2 ? <div className="message-search-results">{searchResults.data?.map((item) => <button key={item.id} onClick={() => { if (item.peer) setParams({ peer: item.peer.id }); setQuery(""); }}><strong>{item.peer?.name}</strong><span>{item.body}</span></button>)}{!searchResults.isLoading && !searchResults.data?.length ? <small>Sonuç bulunamadı.</small> : null}</div> : <>
      <label className="new-conversation-field">Yeni konuşma<input value={recipientQuery} onFocus={() => setRecipientFocused(true)} onBlur={() => window.setTimeout(() => setRecipientFocused(false), 150)} onChange={(event) => setRecipientQuery(event.target.value)} placeholder="Kullanıcı adı veya ad yaz…"/></label>
      {recipientQuery.trim().length >= 2 ? <div className="message-search-results">{recipientResults.data?.items.filter((item) => item.kind === "user").map((item) => <button key={item.id} onClick={() => { setParams({ peer: item.id }); setRecipientQuery(""); }}><strong>{item.title}</strong><span>{item.subtitle}</span></button>)}{!recipientResults.isLoading && !recipientResults.data?.items.some((item) => item.kind === "user") ? <small>Kullanıcı bulunamadı.</small> : null}</div> : recipientFocused ? <div className="message-search-results"><small>Öneriler</small>{newRecipients.slice(0, 5).map((member) => <button key={member.id} onClick={() => setParams({ peer: member.id })}><strong>{member.username ? `@${member.username}` : member.name}</strong></button>)}</div> : null}
      <div className="conversation-list">{list.map((conversation) => <button className={conversation.peer.id === peerId ? "conversation-card is-active" : "conversation-card"} key={conversation.peer.id} onClick={() => setParams({ peer: conversation.peer.id })}><span className="conversation-avatar">{conversation.peer.name[0]}</span><span><strong>{conversation.peer.name}{conversation.preference?.pinned ? <Pin size={12}/> : null}{conversation.preference?.muted ? <VolumeX size={12}/> : null}</strong><small>{conversation.lastMessage.attachmentUrl ? "📎 " : ""}{conversation.lastMessage.body}</small></span>{conversation.unreadCount ? <b>{conversation.unreadCount}</b> : null}</button>)}{!list.length ? <p className="form-help">Henüz konuşman yok.</p> : null}</div></>}
    </aside>
    <div className="message-thread">{peer ? <MessageThread peer={peer} messages={messages.data?.items ?? []} currentUserId={user.id} typing={Boolean(typing.data?.typing)} preference={selectedConversation?.preference} onBack={() => setParams({})} onChanged={refresh}/> : <div className="empty-state"><MessageCircle size={44}/><h2>Bir konuşma seç</h2><p>Mesajların burada görüntülenecek.</p></div>}</div>
  </section>;
}

function MessageThread({ peer, messages, currentUserId, typing, preference, onBack, onChanged }: { peer: { id: string; name: string; username?: string | null }; messages: PrivateChatMessage[]; currentUserId: string; typing: boolean; preference?: { pinned: boolean; muted: boolean; archived: boolean }; onBack: () => void; onChanged: () => void }) {
  const [body, setBody] = useState(""); const [replyTo, setReplyTo] = useState<PrivateChatMessage | null>(null); const [editing, setEditing] = useState<PrivateChatMessage | null>(null); const [attachments, setAttachments] = useState<File[]>([]); const [menu, setMenu] = useState(false); const fileRef = useRef<HTMLInputElement>(null); const textRef = useRef<HTMLTextAreaElement>(null); const streamRef = useRef<HTMLDivElement>(null); const typingTimer = useRef<number | undefined>(undefined);
  const previews = useMemo(() => attachments.map((file) => ({ file, url: URL.createObjectURL(file) })), [attachments]);
  useEffect(() => () => previews.forEach((preview) => URL.revokeObjectURL(preview.url)), [previews]);
  const send = useMutation({ mutationFn: async () => { if (!attachments.length) return sendPrivateMessage(peer.id, body, { replyToId: replyTo?.id }); let last: PrivateChatMessage | undefined; for (const [index, attachment] of attachments.entries()) last = await sendPrivateMessage(peer.id, index === 0 ? body || "Medya" : "Medya", { replyToId: index === 0 ? replyTo?.id : undefined, attachment }); return last!; }, onSuccess: () => { setBody(""); setReplyTo(null); setAttachments([]); onChanged(); } });
  const edit = useMutation({ mutationFn: () => editPrivateMessage(editing!.id, body), onSuccess: () => { setBody(""); setEditing(null); onChanged(); } });
  const remove = useMutation({ mutationFn: deletePrivateMessage, onSuccess: onChanged });
  const react = useMutation({ mutationFn: ({ id, emoji }: { id: string; emoji: string }) => toggleMessageReaction(id, emoji), onSuccess: onChanged });
  const preferenceMutation = useMutation({ mutationFn: (input: { pinned?: boolean; muted?: boolean; archived?: boolean }) => updateConversationPreference(peer.id, input), onSuccess: () => { setMenu(false); onChanged(); } });
  const deleteConversationMutation = useMutation({ mutationFn: () => deleteConversation(peer.id), onSuccess: () => { setMenu(false); onChanged(); onBack(); } });
  const blockMutation = useMutation({ mutationFn: () => createBlock("user", peer.id), onSuccess: () => { setMenu(false); onChanged(); onBack(); } });
  useEffect(() => { streamRef.current?.scrollTo({ top: streamRef.current.scrollHeight }); }, [messages.length]);
  useEffect(() => { const textarea = textRef.current; if (!textarea) return; textarea.style.height = "42px"; textarea.style.height = `${Math.min(textarea.scrollHeight, 120)}px`; }, [body]);
  function type(value: string) { setBody(value); window.clearTimeout(typingTimer.current); void sendTyping(peer.id); typingTimer.current = window.setTimeout(() => undefined, 3000); }
  function submit(event: FormEvent) { event.preventDefault(); if (!body.trim() && !attachments.length) return; if (editing) edit.mutate(); else send.mutate(); }
  return <><header className="message-thread-header"><button className="ghost-action messages-back" onClick={onBack}><ArrowLeft size={18}/> Geri</button><UserIdentityLink user={peer} avatarClassName="thread-peer-avatar" showName={false}/><div><Link to={userProfilePath(peer)}><strong>{peer.name}</strong></Link><span>{typing ? "yazıyor…" : peer.username ? `@${peer.username}` : "Konnektora üyesi"}</span></div><div className="thread-menu"><button onClick={() => setMenu((value) => !value)}><MoreVertical size={19}/></button>{menu ? <div><button onClick={() => preferenceMutation.mutate({ pinned: !preference?.pinned })}><Pin size={15}/>{preference?.pinned ? "Sabitlemeyi kaldır" : "Sabitle"}</button><button onClick={() => preferenceMutation.mutate({ muted: !preference?.muted })}>{preference?.muted ? <Volume2 size={15}/> : <VolumeX size={15}/>}{preference?.muted ? "Sesi aç" : "Sessize al"}</button><button disabled={deleteConversationMutation.isPending} onClick={() => window.confirm("Bu konuşma senden silinsin mi?") && deleteConversationMutation.mutate()}><Trash2 size={15}/>Konuşmayı sil</button><button disabled={blockMutation.isPending} onClick={() => window.confirm(`${peer.name} engellensin mi?`) && blockMutation.mutate()}><Ban size={15}/>Kullanıcıyı engelle</button></div> : null}</div></header>
    <div className="message-stream" ref={streamRef} aria-live="polite">{messages.map((message) => <MessageBubble key={message.id} message={message} mine={message.senderId === currentUserId} currentUserId={currentUserId} onReply={() => { setReplyTo(message); setEditing(null); }} onEdit={() => { setEditing(message); setReplyTo(null); setBody(message.body); }} onDelete={() => window.confirm("Mesaj silinsin mi?") && remove.mutate(message.id)} onReact={(emoji) => react.mutate({ id: message.id, emoji })}/>)}{typing ? <div className="typing-bubble"><i/><i/><i/></div> : null}{!messages.length ? <p className="empty-state">İlk mesajı sen gönder.</p> : null}</div>
    {(replyTo || editing) ? <div className="composer-context"><div>{replyTo ? <><Reply size={15}/><span><strong>{replyTo.senderId === currentUserId ? "Sen" : peer.name}</strong>{replyTo.body}</span></> : <><Edit3 size={15}/><span><strong>Mesajı düzenle</strong>{editing?.body}</span></>}</div><button onClick={() => { setReplyTo(null); setEditing(null); setBody(""); }}><X size={17}/></button></div> : null}
    {previews.length ? <div className="message-attachment-previews">{previews.map(({ file, url }, index) => <div key={`${file.name}-${file.lastModified}`}><span>{file.type.startsWith("video/") ? <video src={url}/> : <img src={url} alt={file.name}/>}</span><small>{file.name}</small><button aria-label={`${file.name} ekini kaldır`} onClick={() => setAttachments((items) => items.filter((_, itemIndex) => itemIndex !== index))} type="button"><X size={14}/></button></div>)}</div> : null}
    <form className="message-composer advanced-composer" onSubmit={submit}><input ref={fileRef} hidden multiple type="file" accept="image/*,video/*" onChange={(event) => { const selected = [...(event.target.files ?? [])].filter((file) => file.type.startsWith("image/") || file.type.startsWith("video/")); setAttachments((items) => [...items, ...selected].slice(0, 6)); event.target.value = ""; }}/><textarea ref={textRef} aria-label="Mesaj" value={body} onChange={(event) => type(event.target.value)} maxLength={5000} placeholder="Bir mesaj yaz…" rows={3}/><button className="message-media-action" type="button" title="Resim/video ekle" onClick={() => fileRef.current?.click()}><ImagePlus size={18}/><span>Resim/video ekle</span></button><button className="primary-action" disabled={send.isPending || edit.isPending}><Send size={18}/><span>Gönder</span></button></form></>;
}

function MessageBubble({ message, mine, currentUserId, onReply, onEdit, onDelete, onReact }: { message: PrivateChatMessage; mine: boolean; currentUserId: string; onReply: () => void; onEdit: () => void; onDelete: () => void; onReact: (emoji: string) => void }) {
  const [actions, setActions] = useState(false); const [reportOpen, setReportOpen] = useState(false); const grouped = useMemo(() => Object.entries((message.reactions ?? []).reduce<Record<string, string[]>>((all, reaction) => ({ ...all, [reaction.emoji]: [...(all[reaction.emoji] ?? []), reaction.userId] }), {})), [message.reactions]);
  return <><article className={mine ? "message-bubble is-mine" : "message-bubble"}><div className="bubble-actions"><button onClick={onReply} title="Yanıtla"><Reply size={14}/></button><button onClick={() => setActions((value) => !value)} title="Tepki"><Smile size={14}/></button>{!mine ? <button onClick={() => setReportOpen(true)} title="Rapor et"><Flag size={14}/></button> : null}{mine && message.status === "active" ? <><button onClick={onEdit} title="Düzenle"><Edit3 size={14}/></button><button onClick={onDelete} title="Sil"><Trash2 size={14}/></button></> : null}</div>{actions ? <div className="reaction-picker">{emojis.map((emoji) => <button key={emoji} onClick={() => { onReact(emoji); setActions(false); }}>{emoji}</button>)}</div> : null}{message.replyTo ? <div className="reply-preview"><Reply size={13}/>{message.replyTo.body}</div> : null}<p className={message.status === "deleted" ? "deleted-message" : ""}><RichText text={message.body}/></p>{message.attachmentUrl ? message.attachmentType?.startsWith("image/") ? <a href={message.attachmentUrl} target="_blank"><img className="message-image" src={message.attachmentUrl} alt={message.attachmentName ?? "Mesaj görseli"}/></a> : <a className="message-file" href={message.attachmentUrl} target="_blank"><File size={18}/><span>{message.attachmentName ?? "Dosya"}<small>{message.attachmentSize ? `${Math.ceil(message.attachmentSize / 1024)} KB` : ""}</small></span></a> : null}<footer><time>{new Intl.DateTimeFormat("tr-TR", { hour: "2-digit", minute: "2-digit" }).format(new Date(message.createdAt))}{message.editedAt ? " · düzenlendi" : ""}</time>{mine ? message.readAt ? <CheckCheck size={15} aria-label="Okundu"/> : <Check size={15} aria-label="Gönderildi"/> : null}</footer>{grouped.length ? <div className="message-reactions">{grouped.map(([emoji, users]) => <button className={users.includes(currentUserId) ? "active" : ""} key={emoji} onClick={() => onReact(emoji)}>{emoji} {users.length}</button>)}</div> : null}</article><ReportDialog onClose={() => setReportOpen(false)} open={reportOpen} targetId={message.id} targetType="private_message"/></>;
}
