import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Crown, Sparkles, Store } from "lucide-react";
import { Link } from "react-router-dom";
import { changeMemberPlan, getFinanceDashboard, getUserSession } from "../lib/api";

const plans = [
  { id: "free", name: "Ücretsiz", price: "₺0", icon: <Store/>, features: ["Topluluğu ve içerikleri keşfet", "Etkinliklere katıl", "Temel profil ve mesajlaşma"] },
  { id: "plus", name: "Plus", price: "₺99 / ay", icon: <Sparkles/>, features: ["Gelişmiş kişi ve etkinlik önerileri", "Daha fazla profil medyası", "Öncelikli destek"] },
  { id: "premium", name: "Premium", price: "₺249 / ay", icon: <Crown/>, features: ["Tüm Plus özellikleri", "Gelişmiş eşleşme içgörüleri", "Özel topluluk avantajları"] }
] as const;
export function StorePage() { const user = getUserSession(); const client = useQueryClient(); const finance = useQuery({ queryKey: ["finance"], queryFn: getFinanceDashboard, enabled: Boolean(user) }); const select = useMutation({ mutationFn: (plan: "free" | "plus" | "premium") => changeMemberPlan(plan, plan === "free" ? undefined : `pm_sandbox_${crypto.randomUUID()}`), onSuccess: () => client.invalidateQueries({ queryKey: ["finance"] }) }); return <div className="page member-store"><header><span className="eyebrow">Konnektora mağaza</span><h1>Deneyimini sana uygun paketle güçlendir.</h1><p>Ücretsiz başla; daha gelişmiş keşif ve topluluk araçlarına ihtiyaç duyduğunda paketini değiştir.</p></header><section>{plans.map((plan) => <article className={finance.data?.member.plan === plan.id ? "selected" : ""} key={plan.id}>{plan.icon}<h2>{plan.name}</h2><strong>{plan.price}</strong><ul>{plan.features.map((feature) => <li key={feature}><Check size={16}/>{feature}</li>)}</ul>{user ? <button className={finance.data?.member.plan === plan.id ? "secondary-action" : "primary-action"} disabled={select.isPending || finance.data?.member.plan === plan.id} onClick={() => select.mutate(plan.id)}>{finance.data?.member.plan === plan.id ? "Aktif paket" : "Paketi seç"}</button> : <Link className="primary-action" to="/login">Giriş yap ve seç</Link>}</article>)}</section>{select.isSuccess ? <p className="form-success">Paketin başarıyla güncellendi.</p> : null}{select.isError ? <p className="form-error">Paket güncellenemedi.</p> : null}</div>; }
